#!/usr/bin/env ruby

require 'abc_data'
require 'json'
require 'tempfile'

if ARGV.size < 2 then
  puts "USAGE: #{File.basename($0)} <a.json> <b.json> [diffParams]"
  exit 1
end

$file_a = ARGV[0]
$file_b = ARGV[1]
$extra_params = ARGV.drop(2).join(' ')

$base_a = File.basename($file_a)
$base_b = File.basename($file_b)

$hash_a = JSON.parse(File.read($file_a))
$hash_b = JSON.parse(File.read($file_b))

$tempfile_a = Tempfile.new($base_a)
$tempfile_b = Tempfile.new($base_b)

$tempfile_a.write(
  JSON.pretty_generate(
    AbcData.order($hash_a)
  )
)
$tempfile_b.write(
  JSON.pretty_generate(
    AbcData.order($hash_b)
  )
)

$tempfile_a.close
$tempfile_b.close

puts `diff #{$tempfile_a.path} #{$tempfile_b.path} #{$extra_params}`
